adding a cd workflow in the actions tab

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -348,6 +348,42 @@ jobs:
       - name: Log out from Docker Hub
         run: docker logout
 
+  ci_pipeline_complete:
+    name: CI Pipeline Complete
+    needs: [backend_docker, frontend_docker]
+    runs-on: ubuntu-latest
+    steps:
+
+      #Check if we reach this step
+      - name: Checkpoint
+        run: echo "✅ Reached CI Pipeline Complete step."
+
+      # Check if pipeline was successful
+      - name: Check pipeline success
+        run: |
+          if [ ${{ needs.backend_docker.result }} == 'success' ] || [ ${{ needs.frontend_docker.result }} == 'success' ]; then
+            echo "✅ At least one Docker build & push succeeded."
+          else
+            echo "❌ Both Docker build & push jobs failed!"
+            exit 1
+          fi
+
+       # Pipeline complete notification 
+      - name: CI Complete Notification
+        run: echo "✅ CI Pipeline completed successfully."
+
+      # Trigger CD workflow
+      - name: Trigger CD Workflow
+        uses: benc-uk/workflow-dispatch@v1
+        with:
+          workflow: cd.yml
+          repo: ${{ github.repository }}
+          ref: DeploymentPipeline
+          inputs: |
+            ci_workflow_run_id: ${{ github.run_id }}
+            ci_conclusion: success
+
+
+      
   
-
-
+   
